version: "3"
services:
  server:
    container_name: "Bugnet_Server"
    build:
      context: ./server/
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - db

  db:
    container_name: "Bugnet_Database"
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bugnet
      - POSTGRES_USER=bugnet
      - PPOSTGRES_PASSWORD=bugnetpassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  - db-data:
