version: "3"
services:
  server:
    container_name: "Bugnet_Server"
    build:
      context: ./server/
    restart: always
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgresql://bugnet:bugnetpassword@Bugnet_Database:5432/bugnet?schema=public
      - SESSION_SECRET=bugnet_session_secret
      - JWT_SECRET=
      - GITHUB_CLIENT=
      - GITHUB_SECRET=
      - GITHUB_CALLBACK=http://localhost:3030/api/v1/auth/github/callback
      - CLIENT_OAUTH_CALLBACK=http://localhost:3030/auth/github/callback
    depends_on:
      - db

  db:
    container_name: "Bugnet_Database"
    image: postgres:13.11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bugnet
      - POSTGRES_USER=bugnet
      - PPOSTGRES_PASSWORD=bugnetpassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
